[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
runner = 'wasm-bindgen-test-runner'

# [build]
# Use sccache to avoid re-compiling static dependencies like OpenCV
# Install it first: cargo install sccache
# Then uncomment the next line:
# rustc-wrapper = "sccache"

[target.aarch64-linux-android]
rustflags = [
    "-C", "target-feature=+neon",
    "-C", "opt-level=3",
    "-C", "link-arg=-Wl,--allow-shlib-undefined",
    "-C", "link-arg=-lc++_shared",
]



